# Generated by Django 5.0.4 on 2024-04-07 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name_acount', models.CharField(max_length=25)),
                ('pass_acount', models.CharField(max_length=25)),
                ('avatar_acount', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('area_admin', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='people',
            name='ApartNum',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='people',
            name='birthday',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='car_card',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='QlChungCu.car_card'),
        ),
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='people',
            name='expiry',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='people',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='people',
            name='sex',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='name_user',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='people',
            name='acount',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='QlChungCu.acount'),
        ),
        migrations.AddField(
            model_name='acount',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QlChungCu.admin'),
        ),
        migrations.AddField(
            model_name='car_card',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QlChungCu.admin'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name_bill', models.CharField(max_length=255)),
                ('money', models.FloatField()),
                ('decription', models.CharField(max_length=255)),
                ('people', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QlChungCu.people')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('stand', models.CharField(max_length=255)),
                ('describe', models.CharField(max_length=255)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QlChungCu.admin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='people',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QlChungCu.box'),
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name_goods', models.CharField(max_length=255)),
                ('img_goods', models.CharField(max_length=255)),
                ('box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QlChungCu.box')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title_letter', models.TextField()),
                ('content', models.TextField()),
                ('img_letter', models.CharField(max_length=255)),
                ('admin_letter', models.ManyToManyField(to='QlChungCu.admin')),
                ('people', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QlChungCu.people')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
