# Generated by Django 5.0.3 on 2024-04-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0003_rename_admin_letter_letters_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='name_people',
            field=models.CharField(max_length=50),
        ),
    ]
