# Generated by Django 5.0.3 on 2024-04-10 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0004_alter_people_name_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='ApartNum',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='acount',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QlChungCu.acount'),
        ),
        migrations.AlterField(
            model_name='people',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='car_card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QlChungCu.car_card'),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='expiry',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='sex',
            field=models.CharField(max_length=20),
        ),
    ]
