# Generated by Django 5.0.4 on 2024-04-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0004_alter_acount_avatar_acount'),
    ]

    operations = [
        migrations.AddField(
            model_name='acount',
            name='role_acount',
            field=models.CharField(choices=[('admin', 'cư dân')], max_length=20, null=True),
        ),
    ]
