# Generated by Django 5.0.4 on 2024-04-29 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0005_acount_role_acount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcountAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('area_admin', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='acount',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QlChungCu.acountadmin'),
        ),
        migrations.AlterField(
            model_name='box',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QlChungCu.acountadmin'),
        ),
        migrations.AlterField(
            model_name='car_card',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QlChungCu.acountadmin'),
        ),
        migrations.AlterField(
            model_name='letters',
            name='admin',
            field=models.ManyToManyField(to='QlChungCu.acountadmin'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
