# Generated by Django 5.0.4 on 2024-04-29 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0007_acountadmin_name_acount_acountadmin_pass_acount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acountadmin',
            old_name='name_acount',
            new_name='nameacount_admin',
        ),
        migrations.RenameField(
            model_name='acountadmin',
            old_name='pass_acount',
            new_name='passacount_admin',
        ),
        migrations.RemoveField(
            model_name='acount',
            name='role_acount',
        ),
    ]
