# Generated by Django 5.0.4 on 2024-04-29 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0005_alter_people_apartnum_alter_people_acount_and_more'),
        ('QlChungCu', '0008_rename_name_acount_acountadmin_nameacount_admin_and_more'),
    ]

    operations = [
    ]
