# Generated by Django 5.0.4 on 2024-04-29 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0009_merge_20240429_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='people',
        ),
        migrations.AddField(
            model_name='bill',
            name='Acount_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QlChungCu.acount'),
        ),
        migrations.AddField(
            model_name='bill',
            name='type_bill',
            field=models.FloatField(default=3),
        ),
    ]
