# Generated by Django 5.0.4 on 2024-05-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0010_remove_bill_people_bill_acount_id_bill_type_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acountadmin',
            name='passacount_admin',
            field=models.IntegerField(max_length=25, null=True),
        ),
    ]
