# Generated by Django 5.0.4 on 2024-05-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0012_alter_acountadmin_passacount_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='acount',
            name='update_acount',
            field=models.BooleanField(default=False),
        ),
    ]
