# Generated by Django 5.0.4 on 2024-05-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0014_remove_people_acount_remove_bill_acount_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
