# Generated by Django 5.0.4 on 2024-05-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0017_user_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='carcard',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='letters',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='active',
            new_name='is_active',
        ),
    ]
