# Generated by Django 5.0.4 on 2024-05-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0018_rename_active_bill_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='box_status',
            field=models.BooleanField(default=0),
        ),
    ]
