# Generated by Django 5.0.4 on 2024-05-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0021_carcard_status_car_carcard_vehicle_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carcard',
            old_name='status_car',
            new_name='status_card',
        ),
    ]
