# Generated by Django 5.0.4 on 2024-05-09 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0023_alter_people_car_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='car_card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QlChungCu.carcard'),
        ),
    ]
