# Generated by Django 5.0.4 on 2024-05-09 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0024_alter_people_car_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='car_card',
        ),
        migrations.AddField(
            model_name='carcard',
            name='people',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='QlChungCu.people'),
        ),
    ]
