# Generated by Django 5.0.4 on 2024-05-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0025_remove_people_car_card_carcard_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box_status',
            field=models.CharField(choices=[('waiting to receive', 'Waiting'), ('received', 'Received')], default='waiting to receive', max_length=50),
        ),
    ]
