# Generated by Django 5.0.4 on 2024-05-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0026_alter_box_box_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='received_Goods',
            field=models.BooleanField(default=0),
        ),
    ]
