# Generated by Django 5.0.4 on 2024-05-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0027_goods_received_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status_bill',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('paid ', 'Paid')], default='Unpaid', max_length=50),
        ),
    ]
