# Generated by Django 5.0.4 on 2024-05-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0028_bill_status_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='type_bill',
            field=models.CharField(choices=[('Electricity', 'Electricity'), ('Water ', 'Water'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
