# Generated by Django 5.0.4 on 2024-05-10 08:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0029_alter_bill_type_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='letters',
            name='title_letter',
            field=models.TextField(null=True),
        ),
    ]
