# Generated by Django 5.0.4 on 2024-05-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0030_alter_letters_content_alter_letters_title_letter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carcard',
            old_name='user_admin',
            new_name='user',
        ),
    ]
