# Generated by Django 5.0.4 on 2024-05-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0031_rename_user_admin_carcard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcard',
            name='status_card',
            field=models.CharField(choices=[('Unconfimred', 'Un'), ('Wait_for_confirmation', 'Wait'), ('Confirmed', 'Confirmer')], default='Wait_for_confirmation', max_length=50),
        ),
    ]
