# Generated by Django 5.0.4 on 2024-05-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0033_alter_user_avatar_acount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='email',
        ),
    ]
