# Generated by Django 5.0.4 on 2024-05-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0034_remove_people_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='ApartNum',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
