# Generated by Django 5.0.4 on 2024-05-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0035_alter_people_apartnum_alter_people_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='identification_card',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
