# Generated by Django 5.0.4 on 2024-05-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0037_bill_trading_code_bill_transaction_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_style',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
