# Generated by Django 5.0.4 on 2024-05-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0039_alter_bill_payment_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcard',
            name='people',
        ),
        migrations.AlterField(
            model_name='goods',
            name='received_Goods',
            field=models.CharField(choices=[('Waiting_to_receive', 'Wtr'), ('Received', 'Received'), ('User_receives_goods', 'Urg')], default='Waiting_to_receive', max_length=50),
        ),
    ]
