# Generated by Django 5.0.4 on 2024-05-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0040_remove_carcard_people_alter_goods_received_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='note',
            field=models.CharField(default='no notes', max_length=255),
        ),
    ]
