# Generated by Django 5.0.4 on 2024-05-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0042_alter_goods_img_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='size',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
