# Generated by Django 5.0.4 on 2024-06-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0044_question_alter_bill_status_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='note',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
