# Generated by Django 5.0.4 on 2024-06-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0045_alter_survey_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='SurveyResponse',
        ),
    ]
