# Generated by Django 5.0.4 on 2024-06-15 10:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QlChungCu', '0049_letters_feedback_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='img_letter',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
