import { StyleSheet } from "react-native";

export default StyleSheet.create({
    statusbar: {
        backgroundColor: "red",
        barStyle: "dark-content",
    },
    top: {
        marginTop: 40,
        flexDirection: "row",
        height: 60,
        marginLeft: 5,
        flexWrap: "wrap",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
    },
    top2: {
        marginTop: 20,
        flexDirection: "row",
        height: 60,
        marginLeft: 5,
        flexWrap: "wrap",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
    },
    TextTop2: {
        fontWeight: "bold",
        textAlign: "center",
        fontSize: 18,
        color: "white",
        marginLeft: 4,
    },
    TextTop3: {
        color: "red",
        fontSize: 14,
    },
    TextTop: {
        fontWeight: "bold",
        textAlign: "center",
        fontSize: 28,
        color: "white",
    },
    icon: {
        backgroundColor: "transparent",
        alignItems: "center",
        justifyContent: "center",
    },
    inputfather: {
        paddingTop: 40,
        alignItems: "center",
        justifyContent: "center",
    },
    input: {
        width: "80%",
        marginTop: 30,
    },
    ForgotPass: {
        marginTop: 10,
        color: "#f18b28",
        fontSize: 18,
    },
    btnLoginfather: {
        marginTop: 320,
        width: "100%",
        height: 50,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    btnLoginfatherPressed: {
        opacity: 0.5,
    },
    btnLoginChildP: {
        width: "100%",
        height: 50,
        borderRadius: 60,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    btnLoginChild: {
        backgroundColor: "#d6dce9",
        width: "50%",
        height: "100%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        bottom: 10,
    },
    inputfatherForgot: {
        paddingTop: 10,
        alignItems: "center",
        justifyContent: "center",
    },
    btnDoneF: {
        width: "100%",
        height: 50,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    btnDone: {
        position: "relative",
        bottom: 10,
        left: "25%",
        backgroundColor: "#d6dce9",
        width: "50%",
        height: 46,
        borderRadius: 60,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
});
