import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        width: "100%",
        height: "100%",
        position: "relative",
    },
    header: {
        marginTop: 20,
        height: 40,
        width: "100%",
        display: "flex",
        flexDirection: "row",
        // justifyContent: "space-between",
        alignItems: "center",
        paddingLeft: 20,
        paddingRight: 20,
    },
    nameHome: {
        marginTop: 20,
        flex: 1,
        alignSelf: "center",
        fontSize: 28,
        fontWeight: "bold",
        color: "#dcd3d1",
        marginLeft: 20,
    },
    ringNumber: {
        position: "absolute",
        right: 24,
        top: 14,
        zIndex: 1,
    },
    ringNum: {
        color: "#ab9570",
    },
    headerIconLeft: {
        marginTop: -20,
    },
    headerIconRight: {
        marginTop: -20,
        marginRight: 20,
    },
    line: {
        paddingTop: 10,
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        fontWeight: 400,
    },
    inline: {
        color: "#dcd3d1",
    },
    hello: {
        display: "flex",
        flexDirection: "row",
        paddingTop: 14,
        paddingLeft: 20,
    },
    helloText: {
        fontSize: 18,
        color: "#dcd3d1",
        marginLeft: 26,
    },
    helloHeart: {},
    introduceHome: {
        width: "100% - 40px",
        height: 86,
        borderRadius: 20,
        marginLeft: 20,
        marginRight: 20,
        marginTop: 20,
        borderColor: "#dbbf98",
        borderWidth: 1,
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 10,
    },
    introduceHomeimg: {
        width: 60,
        height: 60,
        borderColor: "#dbbf98",
        borderWidth: 2,
        backgroundColor: "transparent",
        borderStyle: "dashed",
        padding: 10,
        borderRadius: 30,
    },
    introduceHomeText: {
        paddingRight: 120,
    },
    introduceHomeTextMain: {
        color: "#dcd3d1",
    },
    introduceHomeTextNote: {
        color: "#dcd3d1",
    },
    introduceHomeIcon: {
        marginRight: 35,
        marginBottom: 24,
    },
    introduceHomeInIcon: {},
    utilities: {
        // width: "100% - 60px",
        // backgroundColor: "red",
        height: 400,
        marginLeft: 20,
        marginRight: 20,
        marginTop: 20,
    },
    utilitiesTow: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: 20,
        width: "100%",
    },
    utilitiesChild: {
        backgroundColor: "#201e20",
        width: "49%",
        height: 120,
        borderRadius: 20,
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        borderColor: "#705235",
        borderWidth: 1,
    },
    utilitiesIcon: {
        width: 38,
        height: 38,
        marginLeft: 40,
        padding: 2,
        backgroundColor: "#403b3e",
    },
    utilitiesText: {
        marginLeft: 54,
        fontSize: 18,
        color: "#dedbde",
    },
    bottom: {
        width: "100%",
        height: 60,
        // backgroundColor: "#403b3e",
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        // alignItems: "center",
        paddingTop: 10,
        bottom: 0,
        paddingLeft: 20,
    },
    bottomIcon: {
        width: "25%",
    },
    bottomIconChild: {
        marginLeft: 54,
        height: 36,
        width: 64,
        backgroundColor: "#dcd3d1",
        borderRadius: 20,
    },

    btnPressedOpacity: {
        opacity: 0.5,
    },
    TextTop: {
        marginTop: 60,
        color: "#dedbde",
        fontSize: 18,
        fontWeight: "bold",
        textAlign: "center",
    },
    input: {
        marginTop: 20,
        width: "70%",
        alignSelf: "center",
        // marginLeft: 24,
        // marginRight: 24,
    },
    chooseImg: {
        backgroundColor: "#e6e0ec",
        color: "#494350",
        marginTop: 20,
        fontSize: 10,
        alignSelf: "center",
        padding: 10,
        borderRadius: 30,
        width: 60,
        height: 60,
        textAlign: "center",
    },
    avatar: {
        width: 220,
        height: 220,
        backgroundColor: "red",
        borderRadius: 110,
        alignSelf: "center",
        marginTop: 50,
    },
    btnDone: {
        position: "relative",
        bottom: 10,
        left: "25%",
        backgroundColor: "#d6dce9",
        width: "50%",
        height: 46,
        borderRadius: 60,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    btnLoginfatherPressed: {
        opacity: 0.5,
    },
    // inputcode: {
    //     backgroundColor: "transparent",
    //     width: 20,
    //     borderBottomColor: "red",
    //     borderBottomWidth: 2,
    //     marginLeft: 20,
    // },
    // PaInput: {
    //     display: "flex",
    //     flexDirection: "row",
    //     alignSelf: "center",
    // },
    inputcode: {
        width: "70%",
        alignSelf: "center",
        marginTop: 20,
    },
    TextTop3: {
        alignSelf: "center",
        marginTop: 20,
    },
    btnLoginChildP: {
        backgroundColor: "#d6dce9",
        width: "50%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        bottom: 20,
        alignSelf: "center",
        borderRadius: 20,
    },
    cardContainer: {
        flexDirection: "row",
        padding: 10,
        margin: 10,
        // backgroundColor: "#fff",
        borderRadius: 10,
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 5,
        height: 134,
        width: "95%",
        alignSelf: "center",
    },
    imageContainer: {
        justifyContent: "center",
        alignItems: "center",
        marginRight: 10,
    },
    image: {
        width: 50,
        height: 50,
        borderRadius: 25,
        borderColor: "#333",
        borderWidth: 1,
    },
    infoContainer: {
        flex: 1,
        justifyContent: "center",
    },
    userText: {
        fontSize: 16,
        fontWeight: "bold",
    },
    areaText: {
        fontSize: 14,
        color: "#666",
    },
    complexName: {
        fontSize: 20,
        textAlign: "center",
        fontWeight: "bold",
        color: "blue",
    },
    containerText: {
        marginTop: 20,
        alignSelf: "center",
        width: "90%",
        backgroundColor: "#fff",
        padding: 10,
        borderRadius: 20,
    },
    title: {
        fontWeight: "bold",
        fontSize: 28,
        alignSelf: "center",
        color: "blue",
    },
    text: {
        fontSize: 18,
        padding: 5,
    },
    TopBtn: {
        width: "60%",
        backgroundColor: "#8ebbed",
        alignSelf: "center",
        padding: 10,
        borderRadius: 20,
    },
    TopBtnText: {
        textAlign: "center",
        fontWeight: "bold",
    },
    titlelist: {
        alignSelf: "center",
        color: "red",
        fontSize: 18,
        marginTop: 5,
    },
    padding: {
        paddingBottom: 40,
    },
    margin: {
        marginBottom: 20,
    },
    thank: {
        color: "red",
        fontSize: 10,
    },
    color: {
        backgroundColor: "#00CC33",
    },
});
